<h1 align="center">Toán ứng dụng và thống kê</h1>
<h2 align="center">Đồ án Gauss - Jordan</h2>
<h3 align="center">Ngày: 05/06/2024</h3>

# 1. Thông tin sinh viên

- Họ và tên: Nguyễn Gia Huy
- MSSV: 22127154
- Lớp: 22CLC06

# 2. Giải thuật Gauss - Jordan tìm ma trận nghịch đảo

Giải thuật Gauss-Jordan là một phương pháp dùng để tìm ma trận nghịch đảo của một ma trận vuông $ A $. Dưới đây là các bước chi tiết của giải thuật:

### Bước 1: Tạo Ma Trận Mở Rộng

Cho ma trận vuông $A$ có kích thước $n \times n$. Đầu tiên, tạo ma trận mở rộng $[A | I]$, trong đó $ I $ là ma trận đơn vị cùng kích thước với $ A $:

$ [A | I] = \begin{bmatrix}
a*{11} & a*{12} & \cdots & a*{1n} & | & 1 & 0 & \cdots & 0 \\
a*{21} & a*{22} & \cdots & a*{2n} & | & 0 & 1 & \cdots & 0 \\
\vdots & \vdots & & \vdots & | & \vdots & \vdots & & \vdots \\
a*{n1} & a*{n2} & \cdots & a\_{nn} & | & 0 & 0 & \cdots & 1 \\
\end{bmatrix} $

### Bước 2: Biến Đổi Gauss-Jordan

Sử dụng các phép biến đổi hàng để biến ma trận $ A $ thành ma trận đơn vị $ I $. Đồng thời, áp dụng các phép biến đổi này lên ma trận đơn vị ở nửa phải của ma trận mở rộng. Các phép biến đổi hàng bao gồm:

- **Đổi chỗ hai hàng**: $ R_i \leftrightarrow R_j $
- **Nhân một hàng với một hằng số khác 0**: $ R_i \leftarrow cR_i $
- **Cộng một hàng với một bội số của hàng khác**: $ R_i \leftarrow R_i + cR_j $

Các bước chi tiết như sau:

1. **Bước i từ 1 đến n**:

   - **Chọn phần tử trục (pivot element)**: Chọn phần tử $ a\_{ii} $ (phần tử trên đường chéo chính của ma trận $ A $).
   - **Đổi chỗ hàng**: Nếu $ a\_{ii} = 0 $, đổi chỗ hàng thứ i với một hàng khác có phần tử tương ứng khác 0.
   - **Chia hàng thứ i cho $ a\_{ii} $**: Để biến phần tử $ a\_{ii} $ thành 1.

   $ R*i \leftarrow \frac{R_i}{a*{ii}} $

   - **Biến đổi các hàng khác**: Dùng hàng thứ i để biến tất cả các phần tử khác trên cột thứ i thành 0. Với mỗi hàng $ j \neq i $:

   $ R*j \leftarrow R_j - a*{ji}R_i $

### Bước 3: Kết Quả

Sau khi hoàn thành các bước biến đổi trên, ma trận mở rộng sẽ có dạng: $ [B | C] $

Nếu $ B = I_n $ (ma trận đơn vị), tức là ma trận $ A $ đã được biến đổi thành ma trận đơn vị, nghĩa là $ C $ chính là ma trận nghịch đảo của $ A $. Khi đó, $A^{-1} = C$.


# 3. Cài đặt

## 3.1 Cài đặt không sử dụng thư viện

### 3.1.1 Class `Matrix`

Class Matrix mô phỏng một ma trận 2 chiều và cung cấp một số phương thức hỗ trợ thao tác trên ma trận. Đoạn mã dưới đây chỉ bao gồm các phương thức vừa đủ để giải thuật Gauss-Jordan hoạt động. Mã nguồn đầy đủ của class này có thể được tìm thấy trong file `matrix.py` do em viết tại [đây](https://github.com/HZeroxium/MTH00051).


In [18]:
class Matrix:
    def __init__(self, data: list[list]) -> None:
        self.data = data
        self.rows = len(data)
        self.columns = len(data[0])

    def __str__(self) -> str:
        result = ""
        for i in range(self.rows):
            for j in range(self.columns):
                self.data[i][j] = round(self.data[i][j], 10)
            result += str(self.data[i]) + "\n"
        return result

    def swapRows(self: "Matrix", i: int, j: int) -> None:
        self.data[i], self.data[j] = self.data[j], self.data[i]

    def attach_matrix_horizontal(self: "Matrix", other: "Matrix") -> "Matrix":
        if self.rows != other.rows:
            raise ValueError("Matrices must have the same number of rows")
        new_data = [self.data[i] + other.data[i] for i in range(self.rows)]
        return Matrix(new_data)

    def separate_matrix_horizontal(
        self: "Matrix", index: int
    ) -> tuple["Matrix", "Matrix"]:
        new_data1 = [self.data[i][:index] for i in range(self.rows)]
        new_data2 = [self.data[i][index:] for i in range(self.rows)]
        return Matrix(new_data1), Matrix(new_data2)

    def is_identity(self: "Matrix") -> bool:
        if self.rows != self.columns:
            return False
        for i in range(self.rows):
            for j in range(self.columns):
                if i == j:
                    if self.data[i][j] != 1.0:
                        return False
                else:
                    if self.data[i][j] != 0.0:
                        return False
        return True

    def Gauss_Jordan(self: "Matrix") -> "Matrix":
        for i in range(self.rows):
            if self.data[i][i] == 0:
                for j in range(i + 1, self.rows):
                    if self.data[j][i] != 0:
                        self.swapRows(i, j)
                        break
            if self.data[i][i] == 0:
                continue
            self.data[i] = [x / self.data[i][i] for x in self.data[i]]
            for j in range(self.rows):
                if j != i:
                    self.data[j] = [
                        self.data[j][k] - self.data[j][i] * self.data[i][k]
                        for k in range(self.columns)
                    ]
        return self

Bảng dưới đây mô tả các phương thức của class `Matrix`:

| Phương thức                  | Mô tả                                                                               |
| ---------------------------- | ----------------------------------------------------------------------------------- |
| `__init__`                   | Khởi tạo một đối tượng `Matrix` với dữ liệu đầu vào là một danh sách các danh sách. |
| `__str__`                    | Trả về một chuỗi biểu diễn cho `Matrix`.                                            |
| `swapRows`                   | Đổi chỗ hai hàng trong ma trận.                                                     |
| `attach_matrix_horizontal`   | Nối một ma trận khác vào bên phải của ma trận hiện tại.                             |
| `seperate_matrix_horizontal` | Tách ma trận hiện tại thành hai ma trận con theo chiều ngang.                       |
| `is_identity`                | Kiểm tra xem ma trận có phải là ma trận đơn vị hay không.                           |
| `Gauss_Jordan`               | Biến đổi ma trận hiện tại theo phương pháp Gauss-Jordan.                            |


### 3.1.2 Hàm `inverse(A)`

Trong đó:

- **Input:**: A là một ma trận vuông.
- **Output:**: Ma trận nghịch đảo của A (nếu có). Trường hợp không tồn tại ma trận nghịch đảo, trả về `None` và thông báo "Ma trận không khả nghịch".

Ý tưởng của hàm `inverse(A)`:

- Kiểm tra xem ma trận $ A $ có phải là ma trận vuông hay không. Nếu không, trả về `None`.
- Tạo ma trận mở rộng $ [A | I_n] $. (Với $n$ là số hàng của ma trận $A$).
- Áp dụng phương pháp Gauss-Jordan để biến đổi ma trận mở rộng thành $ [B | C] $.
- Kiểm tra xem ma trận $B$ có phải ma trận đơn vị hay không. Nếu có, trả về ma trận $C = A^{-1}$ (ma trận nghịch đảo của $A$). Ngược lại, trả về `None`.

Đoạn mã bên dưới chứa hàm `inverse(A)` và hàm `get_identity_matrix(n)` để tạo ma trận đơn vị kích thước $ n \times n $.


In [19]:
def get_identity_matrix(n: int) -> Matrix:
    data = [[1 if i == j else 0 for j in range(n)] for i in range(n)]
    return Matrix(data)


def inverse(A: Matrix) -> Matrix:
    """
    Find the inverse of a square matrix using the Gauss-Jordan method.

    Args:
        A (Matrix): The matrix to find the inverse of.

    Returns:
        Matrix: The inverse of the input matrix A.
    """
    if A.rows != A.columns:
        print("Ma trận không vuông")
        return None

    n = A.rows
    I = get_identity_matrix(n)
    augmented_matrix = A.attach_matrix_horizontal(I)
    reduced_matrix = augmented_matrix.Gauss_Jordan()
    _, inverse_matrix = reduced_matrix.separate_matrix_horizontal(n)

    if not _.is_identity():
        return None
    return inverse_matrix

### 3.1.3 Chương trình chính

Chương trình chính nhận danh sách ma trận từ file **Bài tập tuần 3** và in ra ma trận nghịch đảo của từng ma trận. Nếu ma trận không khả nghịch, in ra thông báo "Ma trận không khả nghịch".


In [20]:
matrices: list[Matrix] = [
    Matrix([[1, 2, 1], [3, 7, 3], [2, 3, 4]]),
    Matrix([[1, -1, 2], [1, 1, -2], [1, 1, 4]]),
    Matrix([[1, 2, 3], [2, 5, 3], [1, 0, 8]]),
    Matrix([[-1, 3, -4], [2, 4, 1], [-4, 2, -9]]),
]

n = len(matrices)

for i in range(n):
    print("*** Ma trận câu " + str(i + 1) + ":")
    print(matrices[i])

    print(">>> Ma trận nghịch đảo tương ứng:")
    res = inverse(matrices[i])
    if res is not None:
        print(res)
    else:
        print("!!! Ma trận không khả nghịch")

    print("=" * 50)

*** Ma trận câu 1:
[1, 2, 1]
[3, 7, 3]
[2, 3, 4]

>>> Ma trận nghịch đảo tương ứng:
[9.5, -2.5, -0.5]
[-3.0, 1.0, 0.0]
[-2.5, 0.5, 0.5]

*** Ma trận câu 2:
[1, -1, 2]
[1, 1, -2]
[1, 1, 4]

>>> Ma trận nghịch đảo tương ứng:
[0.5, 0.5, 0.0]
[-0.5, 0.1666666667, 0.3333333333]
[0.0, -0.1666666667, 0.1666666667]

*** Ma trận câu 3:
[1, 2, 3]
[2, 5, 3]
[1, 0, 8]

>>> Ma trận nghịch đảo tương ứng:
[-40.0, 16.0, 9.0]
[13.0, -5.0, -3.0]
[5.0, -2.0, -1.0]

*** Ma trận câu 4:
[-1, 3, -4]
[2, 4, 1]
[-4, 2, -9]

>>> Ma trận nghịch đảo tương ứng:
!!! Ma trận không khả nghịch


## 3.2 Cài đặt sử dụng thư viện


In [21]:
import numpy as np

# Tạo một ma trận vuông A
matrices: list[np.ndarray] = [
    np.array([[1, 2, 1], [3, 7, 3], [2, 3, 4]]),
    np.array([[1, -1, 2], [1, 1, -2], [1, 1, 4]]),
    np.array([[1, 2, 3], [2, 5, 3], [1, 0, 8]]),
    np.array([[-1, 3, -4], [2, 4, 1], [-4, 2, -9]]),
]

n = len(matrices)

for i in range(n):
    if np.linalg.det(matrices[i]) == 0:
        print("!!! Ma trận câu " + str(i + 1) + " không khả nghịch")
    else:
        print("*** Ma trận câu " + str(i + 1) + ":")
        print(matrices[i])

        print(">>> Ma trận nghịch đảo tương ứng:")
        res = np.linalg.inv(matrices[i])
        print(res)

        print("=" * 50)

*** Ma trận câu 1:
[[1 2 1]
 [3 7 3]
 [2 3 4]]
>>> Ma trận nghịch đảo tương ứng:
[[ 9.50000000e+00 -2.50000000e+00 -5.00000000e-01]
 [-3.00000000e+00  1.00000000e+00  1.33226763e-16]
 [-2.50000000e+00  5.00000000e-01  5.00000000e-01]]
*** Ma trận câu 2:
[[ 1 -1  2]
 [ 1  1 -2]
 [ 1  1  4]]
>>> Ma trận nghịch đảo tương ứng:
[[ 0.5         0.5         0.        ]
 [-0.5         0.16666667  0.33333333]
 [ 0.         -0.16666667  0.16666667]]
*** Ma trận câu 3:
[[1 2 3]
 [2 5 3]
 [1 0 8]]
>>> Ma trận nghịch đảo tương ứng:
[[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]]
!!! Ma trận câu 4 không khả nghịch


Trong đoạn mã trên, ta sử dụng thư viện `numpy` để tìm ma trận nghịch đảo. Chi tiết các hàm sử dụng trong đoạn mã trên:

| Hàm             | Mô tả, so sánh                                                                                                                                               |
| --------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| `np.array`      | Chuyển một danh sách các danh sách thành một mảng numpy. Tương tự với class `Matrix` ở phần 3.1.1.                                                           |
| `np.linalg.inv` | Tìm ma trận nghịch đảo của một ma trận. Tuy nhiên, hàm này chỉ hoạt động với ma trận khả nghịch. Nếu ma trận không khả nghịch, hàm sẽ báo lỗi `LinAlgError`. |
| `np.linalg.det` | Tính định thức của một ma trận. Nếu định thức bằng 0, ma trận sẽ không khả nghịch.                                                                           |

Thuật toán sử dụng để tìm ma trận nghịch đảo trong hàm `inv` của `numpy` có thể khác so với Gauss-Jordan. Tuy nhiên, cả hai phương pháp đều cho kết quả chính xác nếu ma trận đầu vào là khả nghịch.

Hàm `inv` trong NumPy sử dụng các thuật toán từ thư viện LAPACK (Linear Algebra PACKage) để tìm ma trận nghịch đảo. Cụ thể, hàm `inv` gọi các hàm trong LAPACK như `dgetrf` và `dgetri` để thực hiện phép phân rã LU và tìm ma trận nghịch đảo.

**Quy trình chi tiết:**

- **Bước 1:** Phân rã LU:
  - Ma trận $A$ được phân rã thành tích của một ma trận dưới tam giác dưới $L$ và một ma trận tam giác trên $U$ sao cho $A = LU$.
  - Trong NumPy, hàm `dgetrf` thực hiện phân rã LU trên một ma trận.
- **Bước 2:** Giải hệ phương trình:
  - sau khi phân rã, để tìm ma trận nghịch đảo, chúng ta cần giải hai hệ phương trình tam giác
  - Đầu tiên, giải hệ phương trình $LY = I$ để tìm ma trận $Y$.
  - Sau đó, giải hệ phương trình $UX = Y$ để tìm ma trận nghịch đảo $X$.
  - Trong NumPy, hàm `dgetri` thực hiện việc giải hệ phương trình tam giác trên.


# 4. Tổng kết

Trong đồ án này, chúng ta đã tìm hiểu về giải thuật Gauss-Jordan để tìm ma trận nghịch đảo của một ma trận vuông. Chúng ta đã cài đặt giải thuật này bằng cả hai cách: không sử dụng thư viện và sử dụng thư viện `numpy`. Cả hai cách đều cho kết quả chính xác nếu ma trận đầu vào là khả nghịch. Về hiệu suất, việc sử dụng thư viện `numpy` sẽ nhanh hơn so với cài đặt thủ công vì thư viện này sử dụng các thuật toán tối ưu từ LAPACK. Tuy nhiên, việc cài đặt thủ công giúp chúng ta hiểu rõ hơn về cách hoạt động của giải thuật Gauss-Jordan.

# 5. Tài liệu tham khảo

Trong quá trình thực hiện đồ án, em đã tham khảo một số tài liệu sau:

- [NumPy Documentation](https://numpy.org/doc/stable/)
