<h1 align="center">Toán ứng dụng và thống kê</h1>
<h2 align="center">Đồ án Gram - Schmidt</h2>
<h3 align="center">Ngày 18/06/2024</h3>

# 1. Thông tin sinh viên

- Họ và tên: Nguyễn Gia Huy
- MSSV: 22127154
- Lớp: 22CLC06

# 2 Giải thuật

## 2.1 Giải thuật Gram-Schmidt 

Thuật toán Gram-Schmidt là một quy trình trực giao hóa các vector trong không gian Euclid. Thuật toán này chuyển đổi một tập hợp các vector tuyến tính độc lập thành một tập hợp các vector trực giao, và nếu cần, thành các vector trực chuẩn.

### 2.1.1 Định nghĩa

Cho một tập hợp các vector $ \{ \mathbf{u}_1, \mathbf{u}_2, \ldots, \mathbf{u}_n \} $ trong không gian vector, chúng ta muốn tìm một tập hợp các vector trực giao $\{ \mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n \} $ sao cho:

1. $\mathbf{v}_1 $ là vector trực giao đầu tiên.
2. $ \mathbf{v}_2 $ trực giao với $ \mathbf{v}_1 $
3. ...
4. $\mathbf{v}_n $ trực giao với tất cả các vector $ \mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_{n-1} $.

### 2.1.2 Quy trình

1. **Khởi tạo**: Đặt $ \mathbf{v}_1 = \mathbf{u}_1 $.

2. **Tiếp tục cho các vector còn lại**:
    $$\mathbf{v}_k = \mathbf{u}_k - \sum_{j=1}^{k-1} \operatorname{proj}_{\mathbf{v}_j} \mathbf{u}_k $$

    với $\operatorname{proj}_{\mathbf{v}_j} \mathbf{u}_k $ là phép chiếu của $\mathbf{u}_k$ lên $\mathbf{v}_j$ :

    $$\operatorname{proj}_{\mathbf{v}_j} \mathbf{u}_k = \frac{\mathbf{u}_k \cdot \mathbf{v}_j}{\mathbf{v}_j \cdot \mathbf{v}_j} \mathbf{v}_j$$

### 2.1.3 Công thức chi tiết

Để tìm vector trực giao thứ $ k $

$$\mathbf{v}_k = \mathbf{u}_k - \sum_{j=1}^{k-1} \frac{\mathbf{u}_k \cdot \mathbf{v}_j}{\mathbf{v}_j \cdot \mathbf{v}_j} \mathbf{v}_j$$

Sau khi đã có các vector trực giao $\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n $, chúng ta có thể chuẩn hóa chúng để tạo thành các vector trực chuẩn $\{ \mathbf{q}_1, \mathbf{q}_2, \ldots, \mathbf{q}_n \} $ bằng cách:

$$\mathbf{q}_k = \frac{\mathbf{q}_k}{\|\mathbf{q}_k\|}$$

## 2.2 Giải thuật phân rã QR

### 2.2.1 Định nghĩa

**Phân rã QR** là một phương pháp để phân rã một ma trận $A$ thành một tích của hai ma trận $Q$ và $R$ sao cho $Q$ là một ma trận trực giao và $R$ là một ma trận tam giác trên.

$$ A = QR $$

### 2.2.2 Quy trình

- **Bước 1**: Xác định $n$ cột của $A = [\mathbf{u}_1, \mathbf{u}_2, \ldots, \mathbf{u}_n]$ là các vector độc lập tuyến tính.
- **Bước 2**: Thực hiện thuật giải Gram_Schmidt để tìm các vector trực giao $\mathbf{v}_1, \mathbf{v}_2, \ldots, \mathbf{v}_n$. Thông báo nếu các cột của A không độc lập tuyến tính và kết thúc thuật toán, ngược lại chuẩn hóa chúng để tạo thành các vector trực chuẩn $\mathbf{q}_1, \mathbf{q}_2, \ldots, \mathbf{q}_n$.
- **Bước 3**: Tạo ma trận $Q = [\mathbf{q}_1, \mathbf{q}_2, \ldots, \mathbf{q}_n]$.
- **Bước 4**: Tính ma trận $R$ bằng cách: $R_{ij} = \mathbf{q}_i \cdot \mathbf{u}_j$
    $$ R = \begin{bmatrix}
    \mathbf{q}_1 \cdot \mathbf{u}_1 & \mathbf{q}_1 \cdot \mathbf{u}_2 & \ldots & \mathbf{q}_1 \cdot \mathbf{u}_n \\
    0 & \mathbf{q}_2 \cdot \mathbf{u}_2 & \ldots & \mathbf{q}_2 \cdot \mathbf{u}_n \\
    \vdots & \vdots & \ddots & \vdots \\
    0 & 0 & \ldots & \mathbf{q}_n \cdot \mathbf{u}_n
    \end{bmatrix} $$

# 3. Cài đặt

## 3.1 Cài đặt không sử dụng thư viện

### 3.1 Lớp `Vector`

Lớp `Vector` mô tả một vector trong không gian Euclid và cung cấp các phương thức để thực hiện các phép toán trên vector để hỗ trợ việc tính toán trong đồ án lần này. Đoạn mã dưới đây chỉ bao gồm các phương thức vừa đủ để giải thuật Gram-Schmidt và phân rã QR hoạt động. Mã đầy đủ có thể được tìm thấy trong file `vector.py` do em viết tại [đây](https://github.com/HZeroxium/MTH00051)

In [40]:
class Vector:
    def __init__(self, data: list) -> None:
        self.data = data
        self.dimensions = len(data)

    def scale(self, scalar: float) -> "Vector":
        return Vector([x * scalar for x in self.data])

    def calDotProduct(self, other) -> float:
        if self.dimensions != other.dimensions:
            raise ValueError("Vectors must have the same dimensions")
        return sum([self.data[i] * other.data[i] for i in range(self.dimensions)])

    def magnitude(self) -> float:
        return sum([x**2 for x in self.data]) ** 0.5

    def unitize(self) -> "Vector":
        return self.scale(1 / self.magnitude())

    def __iter__(self):
        return iter(self.data)

    def __add__(self, other: "Vector") -> "Vector":
        if self.dimensions != other.dimensions:
            raise ValueError("Vectors must have the same dimensions")
        return Vector([self.data[i] + other.data[i] for i in range(self.dimensions)])

    def __sub__(self, other: "Vector") -> "Vector":
        if self.dimensions != other.dimensions:
            raise ValueError("Vectors must have the same dimensions")
        return Vector([self.data[i] - other.data[i] for i in range(self.dimensions)])

Bảng dưới đây mô tả ngắn gọn các phương thức của lớp `Vector`:

| Phương thức | Mô tả |
| --- | --- |
| `__init__` | Khởi tạo một vector với các giá trị cho trước được lưu trong một list `data` và có số chiều `dimensions` |
| `scale` | Nhân vector với một số vô hướng |
| `calDotProduct` | Tính tích vô hướng với một vector khác |
| `magnitude` | Tính độ dài của vector |
| `unitize` | Chuẩn hóa vector |
| `__iter__` | Cho phép duyệt qua các phần tử của vector |
| `__add__` | Cộng hai vector |
| `__sub__` | Trừ hai vector |

### 3.1.2 Lớp `Matrix`

Lớp `Matrix` mô phỏng một ma trận 2 chiều và cung cấp một số phương thức hỗ trợ thao tác trên ma trận. Đoạn mã dưới đây chỉ bao gồm các phương thức vừa đủ để giải thuật phân rã QR hoạt động. Mã nguồn đầy đủ của lớp này có thể được tìm thấy trong file `matrix.py` do em viết tại [đây](https://github.com/HZeroxium/MTH00051).

In [41]:
class Matrix:
    def __init__(self, data: list[list]) -> None:
        self.data = data
        self.rows = len(data)
        self.columns = len(data[0])

    def __str__(self) -> str:
        result = ""
        for i in range(self.rows):
            for j in range(self.columns):
                self.data[i][j] = round(self.data[i][j], 2)
            result += str(self.data[i]) + "\n"
        return result

    def transpose(self) -> "Matrix":
        new_data = []
        for j in range(self.columns):
            new_data.append([self.data[i][j] for i in range(self.rows)])
        return Matrix(new_data)

    def __mul__(self, other: "Matrix") -> "Matrix":
        new_data = []
        if type(other) == Matrix:
            if self.columns != other.rows:
                raise ValueError(
                    "The number of columns in the first matrix must be equal to the number of rows in the second matrix"
                )
            for i in range(self.rows):
                new_data.append(
                    [
                        sum(
                            [
                                self.data[i][k] * other.data[k][j]
                                for k in range(self.columns)
                            ]
                        )
                        for j in range(other.columns)
                    ]
                )
        elif type(other) == int or type(other) == float:
            new_data = [[x * other for x in row] for row in self.data]
        return Matrix(new_data)

Bảng dưới đây mô tả ngắn gọn các phương thức của lớp `Matrix`:

| Phương thức | Mô tả |
| --- | --- |
| `__init__` | Khởi tạo một ma trận với các giá trị cho trước được lưu trong một list 2 chiều `data`, số hàng `rows` và số cột `cols` |
| `__str__` | Trả về một chuỗi biểu diễn ma trận |
| `transpose` | Trả về ma trận chuyển vị của ma trận hiện tại |
| `__mul__` | Nhân ma trận với một ma trận hoặc một số |


### 3.1.3 Hàm `gram_schmidt`

Hàm `gram_schmidt` thực hiện phép trực giao hóa trên một tập hợp các vector cho trước. Hàm này trả về một `list[Vector]` chứa các vector trực giao.


In [42]:
def gram_schmidt(vectors: list[Vector]) -> list[Vector]:
    basis: list[Vector] = []
    for u in vectors:
        temp = Vector([0] * u.dimensions)
        if len(basis) == 0:
            basis.append(u)
            continue
        for v in basis:
            temp = temp + v.scale(u.calDotProduct(v) / v.calDotProduct(v))
        temp = u - temp
        if temp.magnitude() != 0:
            basis.append(temp)
        else:
            raise ValueError("Vectors must be linearly independent")
    return basis

### 3.1.4 Hàm `qr_decomposition`

Hàm `qr_decomposition` thực hiện phân rã QR trên một ma trận cho trước. Hàm này trả về một cặp `(Q, R)` trong đó `Q` là ma trận trực giao và `R` là ma trận tam giác trên.

In [43]:
def qr_decomposition(matrix: Matrix) -> tuple[Matrix, Matrix]:
    vectors_u = [Vector(v) for v in matrix.transpose().data]
    vectors_v = gram_schmidt(vectors_u)
    vectors_q = [v.unitize() for v in vectors_v]
    matrix_q = Matrix([v.data for v in vectors_q]).transpose()
    matrix_r = Matrix([[0] * matrix.columns for _ in range(matrix.columns)])
    for i in range(matrix.columns):
        for j in range(i, matrix.columns):
            matrix_r.data[i][j] = vectors_q[i].calDotProduct(vectors_u[j])
    return matrix_q, matrix_r

### 3.1.5 Hàm `main`

Hàm `main` thực hiện các bước sau:

- Tạo danh sách các ma trận từ **Bài tập tuần 2**. `list[Matrix]`
- Duyệt qua từng ma trận, thực hiện phân rã QR và in kết quả.

In [44]:
def main():

    matrices: list[Matrix] = [
        Matrix([[1, 1, 2], [2, -1, 1], [-2, 4, 1]]),
        Matrix([[1, 1, 1], [2, -2, 2], [1, 1, -1]]),
        Matrix([[1, 1, -1], [0, 1, 2], [1, 1, 1]]),
        Matrix([[-1, -1, 1], [1, 3, 3], [-1, -1, 5], [1, 3, 7]]),
        Matrix([[1, 1, 1], [2, 2, 0], [3, 0, 0], [0, 0, 1]]),
        Matrix([[-2, 1, 3], [1, 0, 0], [0, 1, 0], [0, 0, 1]]),
        Matrix([[1, -1, 2], [1, 0, -1], [-1, 1, 2], [0, 1, 1]]),
    ]

    n = len(matrices)
    for i in range(n):
        print("*** Ma trận câu " + chr(ord("a") + i) + ":")
        print(matrices[i])
        matrix_q, matrix_r = qr_decomposition(matrices[i])
        print("--> Ma trận Q:")
        print(matrix_q)
        print("--> Ma trận R:")
        print(matrix_r)
        print("==> Ma trận Q * R:")
        qr: Matrix = matrix_q * matrix_r
        print(qr)
        print("=" * 50)


if __name__ == "__main__":
    main()

*** Ma trận câu a:
[1, 1, 2]
[2, -1, 1]
[-2, 4, 1]

--> Ma trận Q:
[0.33, 0.67, 0.67]
[0.67, 0.33, -0.67]
[-0.67, 0.67, -0.33]

--> Ma trận R:
[3.0, -3.0, 0.67]
[0, 3.0, 2.33]
[0, 0, 0.33]

==> Ma trận Q * R:
[0.99, 1.02, 2.0]
[2.01, -1.02, 1.0]
[-2.01, 4.02, 1.0]

*** Ma trận câu b:
[1, 1, 1]
[2, -2, 2]
[1, 1, -1]

--> Ma trận Q:
[0.41, 0.58, 0.71]
[0.82, -0.58, 0.0]
[0.41, 0.58, -0.71]

--> Ma trận R:
[2.45, -0.82, 1.63]
[0, 2.31, -1.15]
[0, 0, 1.41]

==> Ma trận Q * R:
[1.0, 1.0, 1.0]
[2.01, -2.01, 2.0]
[1.0, 1.0, -1.0]

*** Ma trận câu c:
[1, 1, -1]
[0, 1, 2]
[1, 1, 1]

--> Ma trận Q:
[0.71, 0.0, -0.71]
[0.0, 1.0, 0.0]
[0.71, 0.0, 0.71]

--> Ma trận R:
[1.41, 1.41, 0.0]
[0, 1.0, 2.0]
[0, 0, 1.41]

==> Ma trận Q * R:
[1.0, 1.0, -1.0]
[0.0, 1.0, 2.0]
[1.0, 1.0, 1.0]

*** Ma trận câu d:
[-1, -1, 1]
[1, 3, 3]
[-1, -1, 5]
[1, 3, 7]

--> Ma trận Q:
[-0.5, 0.5, -0.5]
[0.5, 0.5, -0.5]
[-0.5, 0.5, 0.5]
[0.5, 0.5, 0.5]

--> Ma trận R:
[2.0, 4.0, 2.0]
[0, 2.0, 8.0]
[0, 0, 4.0]

==> Ma trận Q 

## 3.2 Cài đặt sử dụng thư viện

Để cài đặt giải thuật Gram-Schmidt và phân rã QR, ta có thể sử dụng thư viện `numpy` để thực hiện các phép toán ma trận và vector. Đoạn mã dưới đây mô tả cách sử dụng thư viện `numpy` để thực hiện phân rã QR.

In [45]:
import numpy as np

matrices_np = [
    np.array([[1, 1, 2], [2, -1, 1], [-2, 4, 1]]),
    np.array([[1, 1, 1], [2, -2, 2], [1, 1, -1]]),
    np.array([[1, 1, -1], [0, 1, 2], [1, 1, 1]]),
    np.array([[-1, -1, 1], [1, 3, 3], [-1, -1, 5], [1, 3, 7]]),
    np.array([[1, 1, 1], [2, 2, 0], [3, 0, 0], [0, 0, 1]]),
    np.array([[-2, 1, 3], [1, 0, 0], [0, 1, 0], [0, 0, 1]]),
    np.array([[1, -1, 2], [1, 0, -1], [-1, 1, 2], [0, 1, 1]]),
]

n = len(matrices_np)
for i in range(n):
    print("*** Ma trận câu " + chr(ord("a") + i) + ":")
    print(matrices_np[i])
    matrix_q_np, matrix_r_np = np.linalg.qr(matrices_np[i])
    print("---> Ma trận Q:")
    print(matrix_q_np)
    print("--> Ma trận R:")
    print(matrix_r_np)
    print("==> Ma trận Q * R:")
    qr_np = np.dot(matrix_q_np, matrix_r_np)
    print(qr_np)
    print("=" * 50)

*** Ma trận câu a:
[[ 1  1  2]
 [ 2 -1  1]
 [-2  4  1]]
---> Ma trận Q:
[[-0.33333333 -0.66666667  0.66666667]
 [-0.66666667 -0.33333333 -0.66666667]
 [ 0.66666667 -0.66666667 -0.33333333]]
--> Ma trận R:
[[-3.          3.         -0.66666667]
 [ 0.         -3.         -2.33333333]
 [ 0.          0.          0.33333333]]
==> Ma trận Q * R:
[[ 1.  1.  2.]
 [ 2. -1.  1.]
 [-2.  4.  1.]]
*** Ma trận câu b:
[[ 1  1  1]
 [ 2 -2  2]
 [ 1  1 -1]]
---> Ma trận Q:
[[-4.08248290e-01  5.77350269e-01 -7.07106781e-01]
 [-8.16496581e-01 -5.77350269e-01 -5.37546367e-17]
 [-4.08248290e-01  5.77350269e-01  7.07106781e-01]]
--> Ma trận R:
[[-2.44948974  0.81649658 -1.63299316]
 [ 0.          2.30940108 -1.15470054]
 [ 0.          0.         -1.41421356]]
==> Ma trận Q * R:
[[ 1.  1.  1.]
 [ 2. -2.  2.]
 [ 1.  1. -1.]]
*** Ma trận câu c:
[[ 1  1 -1]
 [ 0  1  2]
 [ 1  1  1]]
---> Ma trận Q:
[[-7.07106781e-01 -3.35470445e-17 -7.07106781e-01]
 [-0.00000000e+00 -1.00000000e+00  4.74426853e-17]
 [-7.07106781e

Bảng dưới đây mô tả ngắn gọn các phương thức của thư viện `numpy`:

| Phương thức | Mô tả |
| --- | --- |
| `numpy.array` | Chuyển một list thành một mảng numpy |
| `numpy.linalg.qr` | Phân rã QR một ma trận |
| `numpy.dot` | Tích giữa 2 mảng numpy |

Dựa vào kết quả trên, ta thấy về cơ bản cả hai cách cài đặt đều cho kết quả tương tự nhau, chỉ khác về định dạng in ra. Tuy nhiên, việc sử dụng thư viện `numpy` giúp giảm thời gian cài đặt và tối ưu hóa hiệu suất của chương trình.


# 4. Tổng kết

Trong đồ án này, em đã trình bày về giải thuật Gram-Schmidt và phân rã QR. Em đã cài đặt giải thuật này bằng cả hai cách: không sử dụng thư viện và sử dụng thư viện `numpy`. Kết quả của cả hai cách cài đặt đều cho kết quả tương tự nhau, chỉ khác về định dạng in ra. 
- Cài đặt không sử dụng thư viện giúp hiểu rõ hơn về cách hoạt động của giải thuật và cách thức thực hiện các phép toán trên ma trận và vector.
- Cài đặt sử dụng thư viện giúp giảm thời gian cài đặt và tối ưu hóa hiệu suất của chương trình.

# 5. Tài liệu tham khảo

Trong quá trình thực hiện đồ án, em tham khảo một số tài liệu sau:

1. Slide bài giảng
2. [NumPy Documentation](https://numpy.org/doc/stable/)