<h1 align="center">Toán ứng dụng và thống kê - Đồ án Guass</h1>

# 1. Thông tin sinh viên

- Họ và tên: Nguyễn Gia Huy
- MSSV: 22127154
- Lớp: 22CLC06
- Email: <nghuy22@clc.fitus.edu.vn>

# 2. Giải thuật

Hệ PTTT ${Ax=b}$ thường được giải bằng các bước:

- Bước 1. Lập **ma trận bổ sung** (augmented matrix) bằng cách ghép cột $b$ sau ma trận $A: \overline{A}=[A|b].$

- Bước 2. Dùng các phép biến đổi sơ cấp trên dòng để biến đổi $\overline{A}$ thành ma trận tương đương dòng có dạng bậc thang $R$.

- Bước 3. Giải $R$ bằng **phép thế ngược** (back-substitution) để có nghiệm.

## 2.1 Phép khử Guass

**Khử Gauss** (Gaussian elimination) là một cách biến đổi tương đương dòng đưa ma trận về dạng bậc thang. Thuật giải gồm các bước:

- **Bước 1:** Xác định cột trái nhất không chứa toàn số 0.

- **Bước 2:** Đổi chỗ hai dòng, nếu cần thiết, để đưa số hạng khác 0 nào đó ở dưới về đầu cột nhận được ở Bước 1.

  _(Đơn giản nhất, có thể chọn dòng đầu tiên có số hạng khác 0. Phức tạp hơn, chiến lược "partial pivoting" chọn dòng có số hạng có trị tuyệt đối lớn nhất.)_

- **Bước 3:** Với số hạng đầu cột nhận được từ Bước 2 là $a \neq 0$
  , nhân dòng chứa nó với $\frac{1}{a}$ để có số dẫn đầu 1 (leading 1).
  _(Bước này tùy chọn.)_

- **Bước 4:** Cộng một bội số thích hợp của dòng đầu cho từng dòng dưới để biến các số hạng bên dưới số dẫn đầu thành 0.

- **Bước 5:** Che dòng đầu đã làm xong. Lặp lại các bước cho đến khi được ma trận bậc thang.

## 2.2 Thuật toán Phép Thế Ngược (Back Substitution)

Sau khi áp dụng phép khử Gauss để biến đổi hệ phương trình thành dạng bậc thang trên, chúng ta có thể sử dụng phép thế ngược để tìm nghiệm của hệ phương trình. Thuật toán phép thế ngược được thực hiện như sau:

- **Bước 1:** Bắt đầu từ phương trình cuối cùng của hệ phương trình (ở dòng cuối cùng của ma trận bậc thang).

- **Bước 2:** Giải phương trình cuối cùng để tìm giá trị của biến số cuối cùng.

- **Bước 3:** Lặp lại quá trình này cho các phương trình phía trên, từ dưới lên trên. Sử dụng giá trị của các biến đã biết từ các bước trước để giải các phương trình còn lại.

- **Bước 4:** Tiếp tục quá trình này cho đến khi tất cả các biến số được tìm thấy.

### 2.2.1 Cụ thể

1. **Giải phương trình cuối cùng:**

   - Giả sử phương trình cuối cùng có dạng $a_{nn} x_n = b_n$. Tính $x_n$ bằng cách:
     $$x_n = \frac{b_n}{a_{nn}}$$

2. **Giải các phương trình phía trên:**

   - Với mỗi dòng $i$ từ $n-1$ đến $1$, giải phương trình dạng:

     $$a_{ii} x_i + a_{i,i+1} x_{i+1} + \cdots + a_{in} x_n = b_i$$

   - Tính $x_i$ bằng cách trừ đi các giá trị đã biết của các biến số phía sau và chia cho hệ số của $x_i$:

     $$x_i = \frac{b_i - \sum_{j=i+1}^{n} a_{ij} x_j}{a_{ii}}$$

3. **Tiếp tục quá trình này cho đến dòng đầu tiên.**


# 3. Cài đặt

## 3.1 Không dùng thư viện

### 3.1.1 Class Matrix

Class Matrix mô phỏng một ma trận 2 chiều và cung cấp các phương thức để thực hiện phép khử Gauss và phép thế ngược. Có một số phương thức không cần thiết cho bài toán này, nhưng chúng được giữ lại để mở rộng cho các bài toán khác.


In [1]:
class Matrix:
    def __init__(self, data: list[list]) -> None:
        self.data = data
        self.rows = len(data)
        self.columns = len(data[0])

    def __str__(self) -> str:
        result = ""
        for i in range(self.rows):
            for j in range(self.columns):
                self.data[i][j] = round(self.data[i][j], 10)
            result += str(self.data[i]) + "\n"
        return result

    def __repr__(self) -> str:
        return f"Matrix({self.data})"

    def __getitem__(self, index: int) -> list:
        return self.data[index]

    def __setitem__(self, index: int, value: list):
        self.data[index] = value

    def __add__(self, other) -> "Matrix":
        if self.rows != other.rows or self.columns != other.columns:
            raise ValueError("Matrices must have the same dimensions")
        new_data = []
        for i in range(self.rows):
            new_data.append(
                [self.data[i][j] + other.data[i][j] for j in range(self.columns)]
            )
        return Matrix(new_data)

    def __sub__(self, other) -> "Matrix":
        if self.rows != other.rows or self.columns != other.columns:
            raise ValueError("Matrices must have the same dimensions")
        new_data = []
        for i in range(self.rows):
            new_data.append(
                [self.data[i][j] - other.data[i][j] for j in range(self.columns)]
            )
        return Matrix(new_data)

    def __mul__(self, other) -> "Matrix":
        if self.columns != other.rows:
            raise ValueError(
                "The number of columns in the first matrix must be equal to the number of rows in the second matrix"
            )
        new_data = []
        for i in range(self.rows):
            new_data.append(
                [
                    sum(
                        [
                            self.data[i][k] * other.data[k][j]
                            for k in range(self.columns)
                        ]
                    )
                    for j in range(other.columns)
                ]
            )
        return Matrix(new_data)

    def getColumn(self: "Matrix", index: int) -> list:
        return [self.data[i][index] for i in range(self.rows)]

    def getRow(self: "Matrix", index: int) -> list:
        return self.data[index]

    def transpose(self) -> "Matrix":
        new_data = []
        for j in range(self.columns):
            new_data.append([self.data[i][j] for i in range(self.rows)])
        return Matrix(new_data)

    def getMinor(self: "Matrix", i: int, j: int) -> "Matrix":
        new_data = [
            [self.data[x][y] for y in range(self.columns) if y != j]
            for x in range(self.rows)
            if x != i
        ]
        return Matrix(new_data)

    def getCofactor(self: "Matrix", i: int, j: int) -> float:
        return self.getMinor(i, j).getDeterminant() * (-1) ** (i + j)

    def getDeterminant(self: "Matrix") -> float:
        if self.rows != self.columns:
            raise ValueError("The matrix must be square")
        if self.rows == 1:
            return self.data[0][0]
        if self.rows == 2:
            return self.data[0][0] * self.data[1][1] - self.data[0][1] * self.data[1][0]
        determinant = 0
        for i in range(self.rows):
            determinant += (
                self.data[0][i] * self.getMinor(0, i).getDeterminant() * (-1) ** i
            )
        return determinant

    def getInverse(self: "Matrix") -> "Matrix":
        determinant = self.getDeterminant()
        if determinant == 0:
            raise ValueError("The matrix is not invertible")
        new_data = [
            [self.getCofactor(i, j) / determinant for j in range(self.columns)]
            for i in range(self.rows)
        ]
        return Matrix(new_data)

    def addColumn(self: "Matrix", column: list) -> "Matrix":
        if len(column) != self.rows:
            raise ValueError("The column must have the same length as the matrix")
        new_data = [self.data[i] + [column[i]] for i in range(self.rows)]
        return Matrix(new_data)

    def separateColumn(self: "Matrix", index: int) -> tuple["Matrix", list]:
        column = self.getColumn(index)
        new_data = [
            self.data[i][:index] + self.data[i][index + 1 :] for i in range(self.rows)
        ]
        return Matrix(new_data), column

    def addRow(self: "Matrix", row: list) -> "Matrix":
        if len(row) != self.columns:
            raise ValueError("The row must have the same length as the matrix")
        new_data = self.data + [row]
        return Matrix(new_data)

    def removeRow(self: "Matrix", index: int) -> "Matrix":
        new_data = self.data[:index] + self.data[index + 1 :]
        return Matrix(new_data)

    def swapRows(self: "Matrix", i: int, j: int) -> None:
        self.data[i], self.data[j] = self.data[j], self.data[i]

    def swapColumns(self: "Matrix", i: int, j: int) -> None:
        for k in range(self.rows):
            self.data[k][i], self.data[k][j] = self.data[k][j], self.data[k][i]

    def getRank(self: "Matrix") -> int:
        rank = 0
        for i in range(self.rows):
            if all([x == 0 for x in self.data[i]]):
                break
            rank += 1
        return rank

Bảng dưới đây mô tả các phương thức của class `Matrix`:

| Phương thức      | Mô tả                                                                               |
| ---------------- | ----------------------------------------------------------------------------------- |
| `__init__`       | Khởi tạo một đối tượng `Matrix` với dữ liệu đầu vào là một danh sách các danh sách. |
| `__str__`        | Trả về một chuỗi biểu diễn cho `Matrix`.                                            |
| `__repr__`       | Trả về một chuỗi biểu diễn chính thức cho `Matrix`.                                 |
| `__getitem__`    | Trả về hàng tại vị trí chỉ mục đã cho.                                              |
| `__setitem__`    | Đặt giá trị cho hàng tại vị trí chỉ mục đã cho.                                     |
| `__add__`        | Thêm hai ma trận lại với nhau.                                                      |
| `__sub__`        | Trừ ma trận này cho ma trận khác.                                                   |
| `__mul__`        | Nhân ma trận này với ma trận khác.                                                  |
| `getColumn`      | Trả về cột tại vị trí chỉ mục đã cho.                                               |
| `getRow`         | Trả về hàng tại vị trí chỉ mục đã cho.                                              |
| `transpose`      | Trả về ma trận chuyển vị của ma trận này.                                           |
| `getMinor`       | Trả về ma trận con tại vị trí chỉ mục đã cho.                                       |
| `getCofactor`    | Trả về cofactor tại vị trí chỉ mục đã cho.                                          |
| `getDeterminant` | Trả về định thức của ma trận.                                                       |
| `getInverse`     | Trả về ma trận nghịch đảo của ma trận này.                                          |
| `addColumn`      | Thêm một cột vào cuối ma trận.                                                      |
| `separateColumn` | Tách một cột ra khỏi ma trận.                                                       |
| `addRow`         | Thêm một hàng vào cuối ma trận.                                                     |
| `removeRow`      | Xóa một hàng khỏi ma trận.                                                          |
| `swapRows`       | Hoán đổi hai hàng trong ma trận.                                                    |
| `swapColumns`    | Hoán đổi hai cột trong ma trận.                                                     |
| `getRank`        | Trả về hạng của ma trận.                                                            |


### 3.1.2 Hàm `Gauss_elimination(A)`:

Trong đó:

- Input: `A` là ma trận bổ sung của hệ phương trình $Ax=b$.
- Output: Ma trận có dạng bậc thang có được từ ma trận bổ sung `A`.


In [2]:
def Gauss_elimination(matrix: "Matrix") -> "Matrix":
    """
    Performs Gaussian elimination on the given matrix.

    Args:
        matrix (Matrix): The matrix to perform Gaussian elimination on.

    Returns:
        Matrix: The matrix after Gaussian elimination has been applied.
    """
    for i in range(matrix.rows):
        pivot = matrix.data[i][i]
        if pivot == 0:
            for j in range(i + 1, matrix.rows):
                if matrix.data[j][i] != 0:
                    matrix.swapRows(i, j)
                    pivot = matrix.data[i][i]
                    break
        if pivot == 0:
            continue
        matrix.data[i] = [x / pivot for x in matrix.data[i]]
        for j in range(i + 1, matrix.rows):
            matrix.data[j] = [
                matrix.data[j][k] - matrix.data[j][i] * matrix.data[i][k]
                for k in range(matrix.columns)
            ]
    return matrix

### 3.1.3 Hàm `back_substitution(A)`:

Trong đó:

- Input: `A` là ma trận bậc thang thu được từ phép khử Gauss của ma trận bổ sung của hệ phương trình $Ax=b$.
- Output: Nghiệm của hệ phương trình $Ax=b$
  - Nếu hệ phương trình vô nghiệm thì trả về `list` rỗng: `[]`
  - Nếu hệ phương trình có nghiệm duy nhất thì trả về `list[float]` chứa các giá trị của các biến số. Ví dụ: Nếu hệ phương trình có 3 biến số $x_1, x_2, x_3$ thì trả về `list` có dạng `[x1, x2, x3`
  - Nếu hệ phương trình có vô số nghiệm thì trả về `list[list]` chứa các giá trị của các biến số. Ví dụ, nếu kết quả trả về là `[[1, 3, 0, 0], [-3, -2, 1, 0], [-1, -4, 0, 1]]` thì $x1 = 1 - 3a - b; x2 = 3 -2a -4b; x3 = a; x4 = b$


In [3]:
def back_substitution(matrix: Matrix) -> list:
    """
    Perform back substitution to solve a system of linear equations represented by a matrix.

    Args:
        matrix (Matrix): The matrix representing the system of linear equations.

    Returns:
        list: The solution(s) to the system of linear equations. If the system has a unique solution,
            a list containing the values of the variables is returned. If the system has infinitely
            many solutions, a list of solution vectors is returned.
    Raises:
        None
    """
    matrix_a, _ = matrix.separateColumn(matrix.columns - 1)
    rankA = matrix_a.getRank()
    rankA_ = matrix.getRank()

    if rankA < rankA_:
        print(">>> Hệ phương trình vô nghiệm")
        return []

    n = matrix.columns - 1
    free_variables = []

    while matrix.rows < matrix.columns - 1:
        matrix = matrix.addRow([0] * matrix.columns)

    while matrix.rows > matrix.columns - 1:
        matrix = matrix.removeRow(matrix.rows - 1)

    # Currently, the matrix is ​​in the form of the above triangular matrix, let's convert it into a main diagonal matrix
    for i in range(matrix.rows):
        if matrix.data[i][i] == 1:
            for j in range(i):
                matrix.data[j] = [
                    matrix.data[j][k] - matrix.data[j][i] * matrix.data[i][k]
                    for k in range(matrix.columns)
                ]
        else:
            if i <= n:
                free_variables.append(i)

    # Unique solution
    if rankA == rankA_ and rankA == n:
        print(">>> Hệ phương trình có nghiệm duy nhất")
        return [matrix[i][n] for i in range(n)]

    # Infinite solutions
    sol = []
    temp = [0] * n
    for i in range(n):
        if i < matrix.rows:
            temp[i] = matrix.data[i][n]
    sol.append(temp)

    # Consider columns that contain free hidden content
    for i in free_variables:
        temp = [0] * n
        temp[i] = 1
        for j in range(n):
            if j != i:
                temp[j] = -matrix.data[j][i]
        sol.append(temp)

    print(">>> Hệ phương trình có vô số nghiệm")
    return sol

### 3.1.4 Chương trình chính

Chương trình chính gồm hàm:

- `roundSol` để làm tròn nghiệm của hệ phương trình để tránh sai số trong việc so sánh.
- `main` để chạy chương trình với các test case đã được cung cấp.


In [4]:
def roundSol(solution: list, n: int) -> list:
    """
    Round the solution to n decimal places.

    Args:
        solution (list): solution to be rounded
        n (int): number of decimal places to round to

    Returns:
        list: solution rounded to n decimal places
    """
    if len(solution) == 0:
        return solution
    if type(solution[0]) != list:
        return [round(x, n) for x in solution]
    len_ = len(solution)
    for i in range(len_):
        solution[i] = [round(x, n) for x in solution[i]]


def main() -> None:

    # Test cases

    # Ma trận hệ số A
    matrices: list[Matrix] = [
        Matrix([[1, 2, -1], [2, 2, 1], [3, 5, -2]]),
        Matrix([[1, -2, -1], [2, -3, 1], [3, -5, 0], [1, 0, 5]]),
        Matrix([[1, 2, 0, 2], [3, 5, -1, 6], [2, 4, 1, 2], [2, 0, -7, 11]]),
        Matrix([[2, -4, -1], [1, -3, 1], [3, -5, -3]]),
        Matrix([[1, 2, -2], [3, -1, 1], [-1, 5, -5]]),
        Matrix([[2, -4, 6], [1, -1, 1], [1, -3, 4]]),
        Matrix([[4, -2, -4, 2], [6, -3, 0, -5], [8, -4, 28, -44], [-8, 4, -4, 12]]),
        Matrix([[1, -2, 3], [2, 2, 0], [0, -3, 4], [1, 0, 1]]),
        Matrix([[3, -3, 3], [-1, -5, 2], [0, -4, 2], [3, -1, 2]]),
        Matrix([[1, -1, 1, -3], [2, -1, 4, -2]]),
        Matrix([[2, -3, 4, -1], [6, 1, -8, 9], [2, 6, 1, -4]]),
        Matrix([[1, 6, 4], [2, 4, -1], [-1, 2, 5]]),
    ]

    # Ma trận hệ số b
    b_list: list[list] = [
        [-1, 1, -1],
        [1, 6, 7, 9],
        [6, 17, 12, 7],
        [1, 1, 2],
        [3, 1, 5],
        [8, -1, 0],
        [1, 3, 11, -5],
        [-3, 0, 1, -1],
        [-3, 4, 2, -4],
        [0, 0],
        [0, 0, 0],
        [0, 0, 0],
    ]

    # Nghiệm của hệ phương trình
    # []: Hệ phương trình vô nghiệm
    # [x1, x2, x3, ...]: Hệ phương trình có nghiệm duy nhất
    # [[x1, x2, x3, ...], [y1, y2, y3, ...], [z1, z2, z3, ...], ...]: Hệ phương trình có vô số nghiệm

    solutions: list[list] = [
        [4, -3, -1],
        [[9, 4, 0], [-5, -3, 1]],
        [2, 3, -2, -1],
        [],
        [[5.0 / 7, 8.0 / 7, 0], [0, 1, 1]],
        [3, 13, 9],
        [[1.0 / 2, 0, 1.0 / 4, 0], [1.0 / 2, 1, 0, 0], [5.0 / 6, 0.0, 4.0 / 3, 1]],
        [-5, 5, 4],
        [[-3.0 / 2, -1.0 / 2, 0.0], [-1.0 / 2, 1.0 / 2, 1]],
        [
            [0, 0, 0, 0],
            [-3, -2, 1, 0],
            [-1, -4, 0, 1],
        ],  # x1 = 0 - 3a - b, x2 = 0 -2a -4b, x3 = 0 + a, x4 = 0 + b
        [
            [0, 0, 0, 0],
            [-19.0 / 50, 16.0 / 25, 23.0 / 25, 1],
        ],
        [[0, 0, 0], [11.0 / 4, -9.0 / 8, 2]],
    ]
    n = len(matrices)
    correct_list = []

    for i in range(n):
        print(
            "** Phép khử Gauss cho ma trận bổ sung của hệ phương trình câu "
            + str(i + 1)
            + ":"
        )
        matrices[i] = matrices[i].addColumn(b_list[i])
        matrix = Gauss_elimination(matrices[i])
        print(matrix)
        print("** Nghiệm của hệ phương trình câu " + str(i + 1) + ":")

        solution = back_substitution(matrix)

        # So sánh nghiệm với kết quả đúng, làm tròn đến 2 chữ số thập phân
        if roundSol(solution, 2) == roundSol(solutions[i], 2):
            correct_list.append(i + 1)

        print(solution)
        print("\n" + "=" * 50 + "\n")

    # Nếu tất cả các hệ phương trình đều giải đúng
    if len(correct_list) == n:
        print("Tất cả các ma trận đều đúng")


if __name__ == "__main__":
    main()

** Phép khử Gauss cho ma trận bổ sung của hệ phương trình câu 1:
[1.0, 2.0, -1.0, -1.0]
[-0.0, 1.0, -1.5, -1.5]
[-0.0, -0.0, 1.0, -1.0]

** Nghiệm của hệ phương trình câu 1:
>>> Hệ phương trình có nghiệm duy nhất
[4.0, -3.0, -1.0]


** Phép khử Gauss cho ma trận bổ sung của hệ phương trình câu 2:
[1.0, -2.0, -1.0, 1.0]
[0.0, 1.0, 3.0, 4.0]
[0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0]

** Nghiệm của hệ phương trình câu 2:
>>> Hệ phương trình có vô số nghiệm
[[9.0, 4.0, 0.0], [-5.0, -3.0, 1]]


** Phép khử Gauss cho ma trận bổ sung của hệ phương trình câu 3:
[1.0, 0.6666666667, 0.0, 0.6666666667, 2.0]
[0.0, 1.0, -0.3333333333, 1.3333333333, 3.6666666667]
[0.0, 0.0, 1.0, -1.5294117647, -0.9411764706]
[0.0, 0.0, 0.0, 1.0, 15.0]

** Nghiệm của hệ phương trình câu 3:
>>> Hệ phương trình có nghiệm duy nhất
[-2.000000000044444, -9.000000000233333, 21.9999999999, 15.0]


** Phép khử Gauss cho ma trận bổ sung của hệ phương trình câu 4:
[1.0, -2.0, -0.5, 0.5]
[-0.0, 1.0, -1.5, -0.5]
[0.0, 0.0, 0.0, 

## 3.2 Dùng thư viện hỗ trợ

Trong Python, thư viện phổ biến để xử lý ma trận, thực hiện phép khử Gauss và tìm nghiệm của hệ phương trình là NumPy, SciPy và SymPy.

- **NumPy** là một thư viện mạnh mẽ cho việc xử lý mảng và ma trận trong Python. NumPy cung cấp các hàm cơ bản để xử lý ma trận, nhưng để thực hiện các thao tác phức tạp hơn như khử Gauss, bạn có thể sử dụng SciPy, một thư viện xây dựng trên NumPy.

- **SciPy** mở rộng chức năng của NumPy bằng cách thêm các công cụ cho các phép toán khoa học và kỹ thuật phức tạp hơn, bao gồm cả việc giải hệ phương trình tuyến tính.

- **SymPy** là một thư viện toán học chuyên sâu cho Python, cung cấp các công cụ để giải các bài toán toán học phức tạp, bao gồm cả giải hệ phương trình tuyến tính.

**Lưu ý:** Để cài đặt thư viện NumPy và SciPy (nếu chưa cài), bạn có thể sử dụng lệnh sau:

```bash
pip install numpy scipy sympy
```

Dưới đây là ví dụ minh họa cách sử dụng NumPy, SciPy và SymPy để giải hệ phương trình tuyến tính:


In [5]:
import numpy as np  # type: ignore
from scipy.linalg import lu, solve
from sympy import symbols, Eq, solve as solve_sympy  # type: ignore

# Khởi tạo ma trận hệ số (A) và vector hằng số (b)

# TH1: Hệ phương trình có nghiệm duy nhất
A3 = np.array([[1, 2, 0, 2], [3, 5, -1, 6], [2, 4, 1, 2], [2, 0, -7, 11]])
b3 = np.array([6, 17, 12, 7])

# Ma trận mở rộng A3|b3
A3_ = np.hstack((A3, b3.reshape(-1, 1)))

# Thực hiện phép khử Gauss bằng phương pháp LU decomposition
P, L, U = lu(A3_)

print("Phân rã LU của ma trận A3|b3, ta được: ")
print("Ma trận P (Ma trận hoán vị):")  # Ma trận hoán vị (permutation matrix)
print(P)

print(
    "Ma trận L (Ma trận tam giác dưới):"
)  # Ma trận tam giác dưới (lower triangular matrix)
print(L)

print(
    "Ma trận U (Ma trận tam giác trên):"
)  # Ma trận tam giác trên (upper triangular matrix)
print(U)

x = solve(A3, b3)
print("Nghiệm của hệ phương trình câu 3:")
print(x)

# TH2: Hệ phương trình vô nghiệm
A4 = np.array([[2, -4, -1], [1, -3, 1], [3, -5, -3]])
b4 = np.array([1, 1, 2])

try:
    x = solve(A4, b4)
    hasNoSolution = True
    for i in x:
        if i < 1e-10:
            hasNoSolution = False
            break
    print("Nghiệm của hệ phương trình câu 4:")
    if hasNoSolution:
        print("Hệ phương trình vô nghiệm")
    else:
        print(x)
except np.linalg.LinAlgError:
    print("Hệ phương trình vô nghiệm")

# TH3: Hệ phương trình có vô số nghiệm
x1, x2, x3, x4 = symbols("x1 x2 x3 x4")
eq1 = Eq(4 * x1 - 2 * x2 - 4 * x3 + 2 * x4, 1)
eq2 = Eq(6 * x1 - 3 * x2 + 0 * x3 - 5 * x4, 3)
eq3 = Eq(8 * x1 - 4 * x2 + 28 * x3 - 44 * x4, 11)
eq4 = Eq(-8 * x1 + 4 * x2 - 4 * x3 + 12 * x4, -5)
solution = solve_sympy((eq1, eq2, eq3, eq4), (x1, x2, x3, x4))
print("Nghiệm của hệ phương trình câu 7:")
print(solution)

Phân rã LU của ma trận A3|b3, ta được: 
Ma trận P (Ma trận hoán vị):
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]
Ma trận L (Ma trận tam giác dưới):
[[ 1.          0.          0.          0.        ]
 [ 0.66666667  1.          0.          0.        ]
 [ 0.66666667 -0.2         1.          0.        ]
 [ 0.33333333 -0.1        -0.75        1.        ]]
Ma trận U (Ma trận tam giác trên):
[[ 3.          5.         -1.          6.         17.        ]
 [ 0.         -3.33333333 -6.33333333  7.         -4.33333333]
 [ 0.          0.          0.4        -0.6        -0.2       ]
 [ 0.          0.          0.          0.25       -0.25      ]]
Nghiệm của hệ phương trình câu 3:
[ 2.  3. -2. -1.]
Nghiệm của hệ phương trình câu 4:
Hệ phương trình vô nghiệm
Nghiệm của hệ phương trình câu 7:
{x1: x2/2 + 5*x4/6 + 1/2, x3: 4*x4/3 + 1/4}


C:\Users\ADMIN\AppData\Local\Temp\ipykernel_18880\1837199078.py:40: LinAlgWarning: Ill-conditioned matrix (rcond=4.62593e-18): result may not be accurate.
  x = solve(A4, b4)


> Đoạn thông báo trên không phải là lỗi mà chỉ là cảnh báo, vì hàm `solve` không thể giải hệ phương trình vô nghiệm. Trong trường hợp này, nó trả về một `list` với các số cực lớn `1.x+e15` và báo rằng kết quả có thể không chính xác.

Trong đoạn mã trên, ta có sử dụng một số hàm như sau:

| Hàm                  | Mô tả, so sánh                                                                                                                                                                                                                                                                                                          |
| -------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `np.array`           | để tạo một mảng NumPy từ một list. Tương tự như class `Matrix` ở phần trước.                                                                                                                                                                                                                                            |
| `np.hstack`          | để nối mảng theo chiều ngang. Tương tự như phương thức `addCol` của class `Matrix`                                                                                                                                                                                                                                      |
| `np.array.reshape`   | để thay đổi kích thước của mảng.                                                                                                                                                                                                                                                                                        |
| `scipy.linalg.lu`    | để thực hiện phân rã LU, tạo ma trận hoán vị `P`, ma trận tam giác dưới `L` và ma trận tam giác trên `U`. Hàm này làm được nhiều hơn so với phép khử Gauss thông thường. Hàm `Gauss_elimination` ở phần trước chỉ thực hiện phép khử Gauss cơ bản trả về ma trận tam giác trên `U` với hệ số ở đường chéo chính bằng 1. |
| `scipy.linalg.solve` | để giải hệ phương trình tuyến tính. Hàm này sử dụng phân rã LU để giải hệ phương trình. Tuy nhiên, hàm chỉ hoạt động nếu ma trận hệ số là ma trận vuông và có nghiệm duy nhất. Trường hợp vô nghiệm hàm sẽ trả về `list` với các số cực lớn `1.x+e15`. Và không thể giải hệ phương trình có vô số nghiệm.               |
| `sympy.symbols`      | để tạo các biến ký hiệu                                                                                                                                                                                                                                                                                                 |
| `sympy.Eq`           | để tạo phương trình tuyến tính                                                                                                                                                                                                                                                                                          |
| `sympy.solve`        | để giải phương trình tuyến tính. Hàm này trả về một `dict` chứa giá trị của các biến số. Nếu hệ phương trình có vô số nghiệm, hàm sẽ trả về `dict` chứa các biến số với giá trị là các biểu thức của các biến khác.                                                                                                     |


# 4. Tổng kết

Trong đồ án này, chúng ta đã tìm hiểu về phương pháp khử Gauss và phép thế ngược để giải hệ phương trình tuyến tính. Chúng ta đã cài đặt thuật toán này bằng cách sử dụng Python và thư viện NumPy, SciPy, SymPy. Bạn có thể sử dụng cả hai cách để giải hệ phương trình tuyến tính, tùy thuộc vào mục tiêu và yêu cầu cụ thể của bài toán. Về ưu, nhược điểm của từng cách có thể được tổng kết như sau:

- **Tự cài đặt thuật toán:**
  - _Ưu điểm:_
    - Hiểu rõ hơn về cách hoạt động của thuật toán.
    - Có thể tùy chỉnh và mở rộng thuật toán theo nhu cầu.
  - _Nhược điểm:_
    - Cần thời gian và công sức để cài đặt và kiểm tra thuật toán.
    - Không hiệu quả cho các bài toán lớn và phức tạp.
- **Sử dụng thư viện hỗ trợ:**
  - _Ưu điểm:_
    - Nhanh chóng và dễ dàng sử dụng.
    - Hỗ trợ nhiều chức năng và bài toán phức tạp.
  - _Nhược điểm:_
    - Không hiểu rõ về cách hoạt động của thuật toán.
    - Không thể tùy chỉnh và mở rộng thuật toán theo nhu cầu.
    - Có thể gặp vấn đề với hiệu suất và tài nguyên cho các bài toán lớn.
    - Có thể gặp vấn đề với sự tương thích và cài đặt.
    - Cần kiểm tra kỹ lưỡng để đảm bảo kết quả chính xác.
    - Không thể giải hết tất cả các trường hợp đặc biệt của hệ phương trình tuyến tính nếu không sử dụng thư viện phù hợp.


# 5. Tài liệu tham khảo

Trong quá trình thực hiện đồ án, em đã tham khảo một số tài liệu sau:

- [NumPy Documentation](https://numpy.org/doc/stable/)
- [SciPy Documentation](https://docs.scipy.org/doc/scipy/)
- [SymPy Documentation](https://docs.sympy.org/latest/index.html)
